FROM alpine:3.19 as node-alpine-3-19

RUN apk add --upgrade --no-cache nodejs npm libuv
RUN apk add --upgrade --no-cache bash
RUN apk add --upgrade --no-cache gcompat

RUN apk add --upgrade --no-cache msttcorefonts-installer
RUN update-ms-fonts

RUN mkdir -p /home/app
WORKDIR /home/app

COPY . /home/app

RUN npm install
RUN npm run build
RUN rm -rf node_modules
RUN npm install --production
RUN npm install -g --production --force --arch=x64 --os=linux --libc=musl sharp

CMD ["npm", "start"]
