name: Dev

on:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [ 18.x, 20.x ]

        steps:
            -   name: Checkout project
                uses: actions/checkout@v3
            -   name: Install and test project with Node v${{ matrix.node-version }}
                uses: actions/setup-node@v3
                with:
                    node-version: ${{ matrix.node-version }}
            -   run: npm install
            -   run: npm test
